<template>
    <div class="page">
<div class="header">
<div class="container">
<p class="title">Privacy Policy for G-mal</p>
<a href="#fr">Français</a>
<a href="#en">English</a>
</div>
</div>

<div class="translations-list-container">
<div class="container">
<ul class="translations-list">
</ul>
</div>
</div>

<div class="translations-content-container">
<div class="container">
<div class="tab-content translations-content-item en visible" id="en">
<h1>Privacy Policy</h1>
<p>Last updated: June 19, 2022</p>
<p>This Privacy Policy describes Our policies and procedures on the 
collection, use and disclosure of Your information when You use the 
Service and tells You about Your privacy rights and how the law protects
 You.</p>
<p>We use Your Personal data to provide and improve the Service. By 
using the Service, You agree to the collection and use of information in
 accordance with this Privacy Policy. This Privacy Policy has been 
created with the help of the <a href="https://www.freeprivacypolicy.com/free-privacy-policy-generator/" target="_blank">Free Privacy Policy Generator</a>.</p>
<h1>Interpretation and Definitions</h1>
<h2>Interpretation</h2>
<p>The words of which the initial letter is capitalized have meanings 
defined under the following conditions. The following definitions shall 
have the same meaning regardless of whether they appear in singular or 
in plural.</p>
<h2>Definitions</h2>
<p>For the purposes of this Privacy Policy:</p>
<ul>
<li>
<p><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p>
</li>
<li>
<p><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to G-mal.</p>
</li>
<li>
<p><strong>Cookies</strong> are small files that are placed on Your 
computer, mobile device or any other device by a website, containing the
 details of Your browsing history on that website among its many uses.</p>
</li>
<li>
<p><strong>Country</strong> refers to: Quebec, Canada</p>
</li>
<li>
<p><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
</li>
<li>
<p><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p>
</li>
<li>
<p><strong>Service</strong> refers to the Website.</p>
</li>
<li>
<p><strong>Service Provider</strong> means any natural or legal person 
who processes the data on behalf of the Company. It refers to 
third-party companies or individuals employed by the Company to 
facilitate the Service, to provide the Service on behalf of the Company,
 to perform services related to the Service or to assist the Company in 
analyzing how the Service is used.</p>
</li>
<li>
<p><strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.</p>
</li>
<li>
<p><strong>Usage Data</strong> refers to data collected automatically, 
either generated by the use of the Service or from the Service 
infrastructure itself (for example, the duration of a page visit).</p>
</li>
<li>
<p><strong>Website</strong> refers to G-mal, accessible from <a href="https://g-mal.ca/" rel="external nofollow noopener" target="_blank">https://g-mal.ca</a></p>
</li>
<li>
<p><strong>You</strong> means the individual accessing or using the 
Service, or the company, or other legal entity on behalf of which such 
individual is accessing or using the Service, as applicable.</p>
</li>
</ul>
<h1>Collecting and Using Your Personal Data</h1>
<h2>Types of Data Collected</h2>
<h3>Personal Data</h3>
<p>While using Our Service, We may ask You to provide Us with certain 
personally identifiable information that can be used to contact or 
identify You. Personally identifiable information may include, but is 
not limited to:</p>
<ul>
<li>
<p>Email address</p>
</li>
<li>
<p>First name and last name</p>
</li>
<li>
<p>Phone number</p>
</li>
<li>
<p>Usage Data</p>
</li>
</ul>
<h3>Usage Data</h3>
<p>Usage Data is collected automatically when using the Service.</p>
<p>Usage Data may include information such as Your Device's Internet 
Protocol address (e.g. IP address), browser type, browser version, the 
pages of our Service that You visit, the time and date of Your visit, 
the time spent on those pages, unique device identifiers and other 
diagnostic data.</p>
<p>When You access the Service by or through a mobile device, We may 
collect certain information automatically, including, but not limited 
to, the type of mobile device You use, Your mobile device unique ID, the
 IP address of Your mobile device, Your mobile operating system, the 
type of mobile Internet browser You use, unique device identifiers and 
other diagnostic data.</p>
<p>We may also collect information that Your browser sends whenever You 
visit our Service or when You access the Service by or through a mobile 
device.</p>
<h3>Information from Third-Party Social Media Services</h3>
<p>The Company allows You to create an account and log in to use the 
Service through the following Third-party Social Media Services:</p>
<ul>
<li>Google</li>
<li>Facebook</li>
<li>Twitter</li>
<li>LinkedIn</li>
</ul>
<p>If You decide to register through or otherwise grant us access to a 
Third-Party Social Media Service, We may collect Personal data that is 
already associated with Your Third-Party Social Media Service's account,
 such as Your name, Your email address, Your activities or Your contact 
list associated with that account.</p>
<p>You may also have the option of sharing additional information with 
the Company through Your Third-Party Social Media Service's account. If 
You choose to provide such information and Personal Data, during 
registration or otherwise, You are giving the Company permission to use,
 share, and store it in a manner consistent with this Privacy Policy.</p>
<h3>Tracking Technologies and Cookies</h3>
<p>We use Cookies and similar tracking technologies to track the 
activity on Our Service and store certain information. Tracking 
technologies used are beacons, tags, and scripts to collect and track 
information and to improve and analyze Our Service. The technologies We 
use may include:</p>
<ul>
<li><strong>Cookies or Browser Cookies.</strong> A cookie is a small 
file placed on Your Device. You can instruct Your browser to refuse all 
Cookies or to indicate when a Cookie is being sent. However, if You do 
not accept Cookies, You may not be able to use some parts of our 
Service. Unless you have adjusted Your browser setting so that it will 
refuse Cookies, our Service may use Cookies.</li>
<li><strong>Flash Cookies.</strong> Certain features of our Service may 
use local stored objects (or Flash Cookies) to collect and store 
information about Your preferences or Your activity on our Service. 
Flash Cookies are not managed by the same browser settings as those used
 for Browser Cookies. For more information on how You can delete Flash 
Cookies, please read "Where can I change the settings for disabling, or 
deleting local shared objects?" available at <a href="https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_" rel="external nofollow noopener" target="_blank">https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_</a></li>
<li><strong>Web Beacons.</strong> Certain sections of our Service and 
our emails may contain small electronic files known as web beacons (also
 referred to as clear gifs, pixel tags, and single-pixel gifs) that 
permit the Company, for example, to count users who have visited those 
pages or opened an email and for other related website statistics (for 
example, recording the popularity of a certain section and verifying 
system and server integrity).</li>
</ul>
<p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies 
remain on Your personal computer or mobile device when You go offline, 
while Session Cookies are deleted as soon as You close Your web browser.
 Learn more about cookies on the <a href="https://www.freeprivacypolicy.com/blog/sample-privacy-policy-template/#Use_Of_Cookies_And_Tracking" target="_blank">Free Privacy Policy website</a> article.</p>
<p>We use both Session and Persistent Cookies for the purposes set out below:</p>
<ul>
<li>
<p><strong>Necessary / Essential Cookies</strong></p>
<p>Type: Session Cookies</p>
<p>Administered by: Us</p>
<p>Purpose: These Cookies are essential to provide You with services 
available through the Website and to enable You to use some of its 
features. They help to authenticate users and prevent fraudulent use of 
user accounts. Without these Cookies, the services that You have asked 
for cannot be provided, and We only use these Cookies to provide You 
with those services.</p>
</li>
<li>
<p><strong>Cookies Policy / Notice Acceptance Cookies</strong></p>
<p>Type: Persistent Cookies</p>
<p>Administered by: Us</p>
<p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
</li>
<li>
<p><strong>Functionality Cookies</strong></p>
<p>Type: Persistent Cookies</p>
<p>Administered by: Us</p>
<p>Purpose: These Cookies allow us to remember choices You make when You
 use the Website, such as remembering your login details or language 
preference. The purpose of these Cookies is to provide You with a more 
personal experience and to avoid You having to re-enter your preferences
 every time You use the Website.</p>
</li>
</ul>
<p>For more information about the cookies we use and your choices 
regarding cookies, please visit our Cookies Policy or the Cookies 
section of our Privacy Policy.</p>
<h2>Use of Your Personal Data</h2>
<p>The Company may use Personal Data for the following purposes:</p>
<ul>
<li>
<p><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</p>
</li>
<li>
<p><strong>To manage Your Account:</strong> to manage Your registration 
as a user of the Service. The Personal Data You provide can give You 
access to different functionalities of the Service that are available to
 You as a registered user.</p>
</li>
<li>
<p><strong>For the performance of a contract:</strong> the development, 
compliance and undertaking of the purchase contract for the products, 
items or services You have purchased or of any other contract with Us 
through the Service.</p>
</li>
<li>
<p><strong>To contact You:</strong> To contact You by email, telephone 
calls, SMS, or other equivalent forms of electronic communication, such 
as a mobile application's push notifications regarding updates or 
informative communications related to the functionalities, products or 
contracted services, including the security updates, when necessary or 
reasonable for their implementation.</p>
</li>
<li>
<p><strong>To provide You</strong> with news, special offers and general
 information about other goods, services and events which we offer that 
are similar to those that you have already purchased or enquired about 
unless You have opted not to receive such information.</p>
</li>
<li>
<p><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</p>
</li>
<li>
<p><strong>For business transfers:</strong> We may use Your information 
to evaluate or conduct a merger, divestiture, restructuring, 
reorganization, dissolution, or other sale or transfer of some or all of
 Our assets, whether as a going concern or as part of bankruptcy, 
liquidation, or similar proceeding, in which Personal Data held by Us 
about our Service users is among the assets transferred.</p>
</li>
<li>
<p><strong>For other purposes</strong>: We may use Your information for 
other purposes, such as data analysis, identifying usage trends, 
determining the effectiveness of our promotional campaigns and to 
evaluate and improve our Service, products, services, marketing and your
 experience.</p>
</li>
</ul>
<p>We may share Your personal information in the following situations:</p>
<ul>
<li><strong>With Service Providers:</strong> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</li>
<li><strong>For business transfers:</strong> We may share or transfer 
Your personal information in connection with, or during negotiations of,
 any merger, sale of Company assets, financing, or acquisition of all or
 a portion of Our business to another company.</li>
<li><strong>With Affiliates:</strong> We may share Your information with
 Our affiliates, in which case we will require those affiliates to honor
 this Privacy Policy. Affiliates include Our parent company and any 
other subsidiaries, joint venture partners or other companies that We 
control or that are under common control with Us.</li>
<li><strong>With business partners:</strong> We may share Your information with Our business partners to offer You certain products, services or promotions.</li>
<li><strong>With other users:</strong> when You share personal 
information or otherwise interact in the public areas with other users, 
such information may be viewed by all users and may be publicly 
distributed outside. If You interact with other users or register 
through a Third-Party Social Media Service, Your contacts on the 
Third-Party Social Media Service may see Your name, profile, pictures 
and description of Your activity. Similarly, other users will be able to
 view descriptions of Your activity, communicate with You and view Your 
profile.</li>
<li><strong>With Your consent</strong>: We may disclose Your personal information for any other purpose with Your consent.</li>
</ul>
<h2>Retention of Your Personal Data</h2>
<p>The Company will retain Your Personal Data only for as long as is 
necessary for the purposes set out in this Privacy Policy. We will 
retain and use Your Personal Data to the extent necessary to comply with
 our legal obligations (for example, if we are required to retain your 
data to comply with applicable laws), resolve disputes, and enforce our 
legal agreements and policies.</p>
<p>The Company will also retain Usage Data for internal analysis 
purposes. Usage Data is generally retained for a shorter period of time,
 except when this data is used to strengthen the security or to improve 
the functionality of Our Service, or We are legally obligated to retain 
this data for longer time periods.</p>
<h2>Transfer of Your Personal Data</h2>
<p>Your information, including Personal Data, is processed at the 
Company's operating offices and in any other places where the parties 
involved in the processing are located. It means that this information 
may be transferred to — and maintained on — computers located outside of
 Your state, province, country or other governmental jurisdiction where 
the data protection laws may differ than those from Your jurisdiction.</p>
<p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
<p>The Company will take all steps reasonably necessary to ensure that 
Your data is treated securely and in accordance with this Privacy Policy
 and no transfer of Your Personal Data will take place to an 
organization or a country unless there are adequate controls in place 
including the security of Your data and other personal information.</p>
<h2>Disclosure of Your Personal Data</h2>
<h3>Business Transactions</h3>
<p>If the Company is involved in a merger, acquisition or asset sale, 
Your Personal Data may be transferred. We will provide notice before 
Your Personal Data is transferred and becomes subject to a different 
Privacy Policy.</p>
<h3>Law enforcement</h3>
<p>Under certain circumstances, the Company may be required to disclose 
Your Personal Data if required to do so by law or in response to valid 
requests by public authorities (e.g. a court or a government agency).</p>
<h3>Other legal requirements</h3>
<p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
<ul>
<li>Comply with a legal obligation</li>
<li>Protect and defend the rights or property of the Company</li>
<li>Prevent or investigate possible wrongdoing in connection with the Service</li>
<li>Protect the personal safety of Users of the Service or the public</li>
<li>Protect against legal liability</li>
</ul>
<h2>Security of Your Personal Data</h2>
<p>The security of Your Personal Data is important to Us, but remember 
that no method of transmission over the Internet, or method of 
electronic storage is 100% secure. While We strive to use commercially 
acceptable means to protect Your Personal Data, We cannot guarantee its 
absolute security.</p>
<h1>Children's Privacy</h1>
<p>Our Service does not address anyone under the age of 13. We do not 
knowingly collect personally identifiable information from anyone under 
the age of 13. If You are a parent or guardian and You are aware that 
Your child has provided Us with Personal Data, please contact Us. If We 
become aware that We have collected Personal Data from anyone under the 
age of 13 without verification of parental consent, We take steps to 
remove that information from Our servers.</p>
<p>If We need to rely on consent as a legal basis for processing Your 
information and Your country requires consent from a parent, We may 
require Your parent's consent before We collect and use that 
information.</p>
<h1>Links to Other Websites</h1>
<p>Our Service may contain links to other websites that are not operated
 by Us. If You click on a third party link, You will be directed to that
 third party's site. We strongly advise You to review the Privacy Policy
 of every site You visit.</p>
<p>We have no control over and assume no responsibility for the content,
 privacy policies or practices of any third party sites or services.</p>
<h1>Changes to this Privacy Policy</h1>
<p>We may update Our Privacy Policy from time to time. We will notify 
You of any changes by posting the new Privacy Policy on this page.</p>
<p>We will let You know via email and/or a prominent notice on Our 
Service, prior to the change becoming effective and update the "Last 
updated" date at the top of this Privacy Policy.</p>
<p>You are advised to review this Privacy Policy periodically for any 
changes. Changes to this Privacy Policy are effective when they are 
posted on this page.</p>
<h1>Contact Us</h1>
<p>If you have any questions about this Privacy Policy, You can contact us:</p>
<ul>
<li>By email: pas.parent@outlook.com</li>
</ul>
</div>
</div>
</div>
<!-- Version francaise -->
<div class="tab-pane fade" id="fr" role="tabpanel" aria-labelledby="fr-tab">
<h1><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Politique de confidentialité</font></font></h1>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Dernière mise à jour : 19 juin 2022</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Cette politique de confidentialité décrit nos politiques et procédures sur la collecte, l'utilisation et la divulgation de vos informations lorsque vous utilisez le service et vous informe sur vos droits en matière de confidentialité et sur la manière dont la loi vous protège.</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Nous utilisons vos données personnelles pour fournir et améliorer le service. </font><font style="vertical-align: inherit;">En utilisant le Service, Vous acceptez la collecte et l'utilisation d'informations conformément à la présente Politique de confidentialité. </font><font style="vertical-align: inherit;">Cette politique de confidentialité a été créée à l'aide du </font></font><a href="https://www.freeprivacypolicy.com/free-privacy-policy-generator/" target="_blank"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">générateur gratuit de politique de confidentialité</font></font></a><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> .</font></font></p>
<h1><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Interprétation et définitions</font></font></h1>
<h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Interprétation</font></font></h2>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Les mots dont la lettre initiale est en majuscule ont des significations définies dans les conditions suivantes. </font><font style="vertical-align: inherit;">Les définitions suivantes auront la même signification qu'elles apparaissent au singulier ou au pluriel.</font></font></p>
<h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Définitions</font></font></h2>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Aux fins de la présente politique de confidentialité&nbsp;:</font></font></p>
<ul>
<li>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Compte</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> désigne un compte unique créé pour vous permettre d'accéder à notre service ou à des parties de notre service.</font></font></p>
</li>
<li>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">La Société</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> (ci-après dénommée «&nbsp;la Société&nbsp;», «&nbsp;Nous&nbsp;», «&nbsp;Notre&nbsp;» ou «&nbsp;Notre&nbsp;» dans le présent Contrat) fait référence à G-mal.</font></font></p>
</li>
<li>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Les cookies</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> sont de petits fichiers qui sont placés sur votre ordinateur, appareil mobile ou tout autre appareil par un site Web, contenant les détails de votre historique de navigation sur ce site Web parmi ses nombreuses utilisations.</font></font></p>
</li>
<li>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Le pays</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> fait référence à&nbsp;: Québec, Canada</font></font></p>
</li>
<li>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Appareil</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> désigne tout appareil pouvant accéder au Service tel qu'un ordinateur, un téléphone portable ou une tablette numérique.</font></font></p>
</li>
<li>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Les données personnelles</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> sont toutes les informations relatives à une personne identifiée ou identifiable.</font></font></p>
</li>
<li>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Le service</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> fait référence au site Web.</font></font></p>
</li>
<li>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Prestataire</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> désigne toute personne physique ou morale qui traite les données pour le compte de la Société. </font><font style="vertical-align: inherit;">Il fait référence à des sociétés tierces ou à des personnes employées par la Société pour faciliter le Service, pour fournir le Service au nom de la Société, pour effectuer des services liés au Service ou pour aider la Société à analyser la manière dont le Service est utilisé.</font></font></p>
</li>
<li>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Le service de médias sociaux tiers</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> fait référence à tout site Web ou à tout site Web de réseau social par lequel un utilisateur peut se connecter ou créer un compte pour utiliser le service.</font></font></p>
</li>
<li>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Les données d'utilisation</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> font référence aux données collectées automatiquement, soit générées par l'utilisation du service, soit à partir de l'infrastructure du service elle-même (par exemple, la durée d'une visite de page).</font></font></p>
</li>
<li>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Le site Web</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> fait référence à G-mal, accessible à partir de </font></font><a href="https://g-mal.ca/" rel="external nofollow noopener" target="_blank"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">https://g-mal.ca</font></font></a></p>
</li>
<li>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Vous</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> désigne la personne accédant ou utilisant le Service, ou la société ou toute autre entité juridique au nom de laquelle cette personne accède ou utilise le Service, selon le cas.</font></font></p>
</li>
</ul>
<h1><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Collecte et utilisation de vos données personnelles</font></font></h1>
<h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Types de données collectées</font></font></h2>
<h3><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Données personnelles</font></font></h3>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Lors de l'utilisation de notre service, nous pouvons vous demander de nous fournir certaines informations personnellement identifiables qui peuvent être utilisées pour vous contacter ou vous identifier. </font><font style="vertical-align: inherit;">Les informations personnellement identifiables peuvent inclure, mais sans s'y limiter&nbsp;:</font></font></p>
<ul>
<li>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Adresse e-mail</font></font></p>
</li>
<li>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Prénom et nom</font></font></p>
</li>
<li>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Numéro de téléphone</font></font></p>
</li>
<li>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Données d'utilisation</font></font></p>
</li>
</ul>
<h3><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Données d'utilisation</font></font></h3>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Les données d'utilisation sont collectées automatiquement lors de l'utilisation du service.</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Les données d'utilisation peuvent inclure des informations telles que l'adresse de protocole Internet de votre appareil (par exemple, l'adresse IP), le type de navigateur, la version du navigateur, les pages de notre service que vous visitez, l'heure et la date de votre visite, le temps passé sur ces pages, l'appareil unique identifiants et autres données de diagnostic.</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Lorsque vous accédez au service par ou via un appareil mobile, nous pouvons collecter automatiquement certaines informations, y compris, mais sans s'y limiter, le type d'appareil mobile que vous utilisez, l'identifiant unique de votre appareil mobile, l'adresse IP de votre appareil mobile, votre système d'exploitation, le type de navigateur Internet mobile que vous utilisez, les identifiants uniques de l'appareil et d'autres données de diagnostic.</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Nous pouvons également collecter des informations que votre navigateur envoie chaque fois que vous visitez notre service ou lorsque vous accédez au service par ou via un appareil mobile.</font></font></p>
<h3><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Informations provenant de services de médias sociaux tiers</font></font></h3>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">La Société vous permet de créer un compte et de vous connecter pour utiliser le service via les services de médias sociaux tiers suivants&nbsp;:</font></font></p>
<ul>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Google</font></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Facebook</font></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Twitter</font></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">LinkedIn</font></font></li>
</ul>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Si vous décidez de vous inscrire ou de nous accorder l'accès à un service de médias sociaux tiers, nous pouvons collecter des données personnelles déjà associées au compte de votre service de médias sociaux tiers, telles que votre nom, votre adresse e-mail, vos activités ou Votre liste de contacts associée à ce compte.</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Vous pouvez également avoir la possibilité de partager des informations supplémentaires avec la Société via le compte de votre service de médias sociaux tiers. </font><font style="vertical-align: inherit;">Si vous choisissez de fournir ces informations et données personnelles, lors de votre inscription ou autrement, vous autorisez la société à les utiliser, les partager et les stocker d'une manière conforme à la présente politique de confidentialité.</font></font></p>
<h3><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Technologies de suivi et cookies</font></font></h3>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Nous utilisons des cookies et des technologies de suivi similaires pour suivre l'activité sur notre service et stocker certaines informations. </font><font style="vertical-align: inherit;">Les technologies de suivi utilisées sont des balises, des balises et des scripts pour collecter et suivre des informations et pour améliorer et analyser notre service. </font><font style="vertical-align: inherit;">Les technologies que nous utilisons peuvent inclure :</font></font></p>
<ul>
<li><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Cookies ou cookies de navigateur. </font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Un cookie est un petit fichier placé sur Votre Appareil. </font><font style="vertical-align: inherit;">Vous pouvez demander à Votre navigateur de refuser tous les Cookies ou de vous signaler l'envoi d'un Cookie. </font><font style="vertical-align: inherit;">Cependant, si vous n'acceptez pas les cookies, vous ne pourrez peut-être pas utiliser certaines parties de notre service. </font><font style="vertical-align: inherit;">À moins que vous n'ayez réglé les paramètres de votre navigateur pour qu'il refuse les cookies, notre service peut utiliser des cookies.</font></font></li>
<li><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Cookies Flash. </font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Certaines fonctionnalités de notre Service peuvent utiliser des objets stockés locaux (ou Flash Cookies) pour collecter et stocker des informations sur Vos préférences ou Votre activité sur notre Service. </font><font style="vertical-align: inherit;">Les cookies Flash ne sont pas gérés par les mêmes paramètres de navigateur que ceux utilisés pour les cookies de navigateur. </font><font style="vertical-align: inherit;">Pour plus d'informations sur la façon dont vous pouvez supprimer les cookies Flash, veuillez lire "Où puis-je modifier les paramètres de désactivation ou de suppression des objets locaux partagés&nbsp;?" </font><font style="vertical-align: inherit;">disponible sur </font></font><a href="https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_" rel="external nofollow noopener" target="_blank"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_</font></font></a></li>
<li><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Balises Web. </font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Certaines sections de notre Service et nos e-mails peuvent contenir de petits fichiers électroniques connus sous le nom de balises Web (également appelés gifs transparents, balises pixel et gifs à pixel unique) qui permettent à la Société, par exemple, de compter les utilisateurs qui ont visité ces pages. ou ouvert un e-mail et pour d'autres statistiques de site Web connexes (par exemple, enregistrer la popularité d'une certaine section et vérifier l'intégrité du système et du serveur).</font></font></li>
</ul>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Les cookies peuvent être des cookies « persistants » ou « de session ». </font><font style="vertical-align: inherit;">Les cookies persistants restent sur votre ordinateur personnel ou votre appareil mobile lorsque vous vous déconnectez, tandis que les cookies de session sont supprimés dès que vous fermez votre navigateur Web. </font><font style="vertical-align: inherit;">En savoir plus sur les cookies sur l' article </font></font><a href="https://www.freeprivacypolicy.com/blog/sample-privacy-policy-template/#Use_Of_Cookies_And_Tracking" target="_blank"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">du site Web Politique de confidentialité gratuite</font></font></a><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> .</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Nous utilisons à la fois des cookies de session et des cookies persistants aux fins décrites ci-dessous&nbsp;:</font></font></p>
<ul>
<li>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Cookies nécessaires / essentiels</font></font></strong></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Type&nbsp;: Cookies de session</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Administré par : Nous</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Objectif : Ces cookies sont essentiels pour vous fournir les services disponibles via le site Web et pour vous permettre d'utiliser certaines de ses fonctionnalités. </font><font style="vertical-align: inherit;">Ils aident à authentifier les utilisateurs et à empêcher l'utilisation frauduleuse des comptes d'utilisateurs. </font><font style="vertical-align: inherit;">Sans ces cookies, les services que vous avez demandés ne peuvent pas être fournis, et nous n'utilisons ces cookies que pour vous fournir ces services.</font></font></p>
</li>
<li>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Politique relative aux cookies / Avis d'acceptation des cookies</font></font></strong></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Type&nbsp;: Cookies persistants</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Administré par : Nous</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Finalité&nbsp;: ces cookies identifient si les utilisateurs ont accepté l'utilisation de cookies sur le site Web.</font></font></p>
</li>
<li>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Cookies de fonctionnalité</font></font></strong></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Type&nbsp;: Cookies persistants</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Administré par : Nous</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Finalité&nbsp;: ces cookies nous permettent de mémoriser les choix que vous faites lorsque vous utilisez le site Web, tels que la mémorisation de vos informations de connexion ou de votre préférence de langue. </font><font style="vertical-align: inherit;">Le but de ces Cookies est de Vous offrir une expérience plus personnelle et de Vous éviter d'avoir à ressaisir vos préférences à chaque fois que Vous utilisez le Site.</font></font></p>
</li>
</ul>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Pour plus d'informations sur les cookies que nous utilisons et vos choix concernant les cookies, veuillez consulter notre Politique de cookies ou la section Cookies de notre Politique de confidentialité.</font></font></p>
<h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Utilisation de vos données personnelles</font></font></h2>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">La Société peut utiliser les Données Personnelles aux fins suivantes :</font></font></p>
<ul>
<li>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Pour fournir et maintenir notre Service</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> , y compris pour surveiller l'utilisation de notre Service.</font></font></p>
</li>
<li>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Pour gérer Votre Compte :</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> pour gérer Votre inscription en tant qu'utilisateur du Service. </font><font style="vertical-align: inherit;">Les données personnelles que vous fournissez peuvent vous donner accès à différentes fonctionnalités du service qui sont à votre disposition en tant qu'utilisateur enregistré.</font></font></p>
</li>
<li>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Pour l'exécution d'un contrat&nbsp;:</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> l'élaboration, la conformité et la réalisation du contrat d'achat des produits, articles ou services que vous avez achetés ou de tout autre contrat avec nous par le biais du service.</font></font></p>
</li>
<li>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Pour vous contacter&nbsp;:</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> pour vous contacter par e-mail, appels téléphoniques, SMS ou autres formes équivalentes de communication électronique, telles que les notifications push d'une application mobile concernant les mises à jour ou les communications informatives relatives aux fonctionnalités, produits ou services sous contrat, y compris les mises à jour de sécurité, lorsque cela est nécessaire ou raisonnable pour leur mise en œuvre.</font></font></p>
</li>
<li>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Pour vous fournir</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> des actualités, des offres spéciales et des informations générales sur d'autres biens, services et événements que nous proposons et qui sont similaires à ceux que vous avez déjà achetés ou demandés, sauf si vous avez choisi de ne pas recevoir ces informations.</font></font></p>
</li>
<li>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Pour gérer vos demandes&nbsp;:</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> pour assister et gérer vos demandes que vous nous adressez.</font></font></p>
</li>
<li>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Pour les transferts d'entreprise&nbsp;:</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> nous pouvons utiliser vos informations pour évaluer ou mener une fusion, une cession, une restructuration, une réorganisation, une dissolution ou toute autre vente ou transfert de tout ou partie de nos actifs, que ce soit dans le cadre d'une entreprise en activité ou dans le cadre d'une faillite, d'une liquidation, ou procédure similaire, dans laquelle les données personnelles que nous détenons sur les utilisateurs de nos services font partie des actifs transférés.</font></font></p>
</li>
<li>
<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">À d'autres fins</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">&nbsp;: nous pouvons utiliser vos informations à d'autres fins, telles que l'analyse de données, l'identification des tendances d'utilisation, la détermination de l'efficacité de nos campagnes promotionnelles et pour évaluer et améliorer notre service, nos produits, nos services, notre marketing et votre expérience.</font></font></p>
</li>
</ul>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Nous pouvons partager vos informations personnelles dans les situations suivantes&nbsp;:</font></font></p>
<ul>
<li><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Avec les fournisseurs de services&nbsp;:</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> nous pouvons partager vos informations personnelles avec des fournisseurs de services pour surveiller et analyser l'utilisation de notre service, pour vous contacter.</font></font></li>
<li><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Pour les transferts d'entreprise&nbsp;:</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> nous pouvons partager ou transférer vos informations personnelles dans le cadre de, ou pendant les négociations de, toute fusion, vente d'actifs de la société, financement ou acquisition de tout ou partie de nos activités à une autre société.</font></font></li>
<li><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Avec les affiliés&nbsp;:</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> nous pouvons partager vos informations avec nos affiliés, auquel cas nous exigerons de ces affiliés qu'ils respectent la présente politique de confidentialité. </font><font style="vertical-align: inherit;">Les sociétés affiliées incluent notre société mère et toutes autres filiales, partenaires de coentreprise ou autres sociétés que nous contrôlons ou qui sont sous contrôle commun avec nous.</font></font></li>
<li><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Avec des partenaires commerciaux&nbsp;:</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> nous pouvons partager vos informations avec nos partenaires commerciaux pour vous proposer certains produits, services ou promotions.</font></font></li>
<li><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Avec d'autres utilisateurs&nbsp;:</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> lorsque vous partagez des informations personnelles ou interagissez autrement dans les zones publiques avec d'autres utilisateurs, ces informations peuvent être vues par tous les utilisateurs et peuvent être diffusées publiquement à l'extérieur. </font><font style="vertical-align: inherit;">Si vous interagissez avec d'autres utilisateurs ou que vous vous inscrivez via un service de médias sociaux tiers, vos contacts sur le service de médias sociaux tiers peuvent voir votre nom, votre profil, vos photos et la description de votre activité. </font><font style="vertical-align: inherit;">De même, les autres utilisateurs pourront voir les descriptions de Votre activité, communiquer avec Vous et consulter Votre profil.</font></font></li>
<li><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Avec votre consentement</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> : Nous pouvons divulguer vos informations personnelles à toute autre fin avec votre consentement.</font></font></li>
</ul>
<h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Conservation de vos données personnelles</font></font></h2>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">La Société ne conservera vos données personnelles que le temps nécessaire aux fins énoncées dans la présente politique de confidentialité. </font><font style="vertical-align: inherit;">Nous conserverons et utiliserons vos données personnelles dans la mesure nécessaire pour nous conformer à nos obligations légales (par exemple, si nous sommes tenus de conserver vos données pour nous conformer aux lois applicables), résoudre les litiges et appliquer nos accords et politiques juridiques.</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">La Société conservera également les données d'utilisation à des fins d'analyse interne. </font><font style="vertical-align: inherit;">Les données d'utilisation sont généralement conservées pendant une période plus courte, sauf lorsque ces données sont utilisées pour renforcer la sécurité ou pour améliorer la fonctionnalité de notre service, ou lorsque nous sommes légalement tenus de conserver ces données pendant des périodes plus longues.</font></font></p>
<h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Transfert de vos données personnelles</font></font></h2>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Vos informations, y compris les données personnelles, sont traitées dans les bureaux d'exploitation de la société et dans tout autre lieu où se trouvent les parties impliquées dans le traitement. </font><font style="vertical-align: inherit;">Cela signifie que ces informations peuvent être transférées et conservées sur des ordinateurs situés en dehors de votre état, province, pays ou autre juridiction gouvernementale où les lois sur la protection des données peuvent différer de celles de votre juridiction.</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Votre consentement à cette politique de confidentialité suivi de votre soumission de ces informations représente votre accord à ce transfert.</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">La société prendra toutes les mesures raisonnablement nécessaires pour garantir que vos données sont traitées en toute sécurité et conformément à la présente politique de confidentialité et aucun transfert de vos données personnelles n'aura lieu vers une organisation ou un pays à moins que des contrôles adéquats ne soient en place, y compris la sécurité de Vos données et autres informations personnelles.</font></font></p>
<h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Divulgation de vos données personnelles</font></font></h2>
<h3><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Transactions commerciales</font></font></h3>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Si la Société est impliquée dans une fusion, une acquisition ou une vente d'actifs, Vos Données Personnelles peuvent être transférées. </font><font style="vertical-align: inherit;">Nous vous informerons avant que vos données personnelles ne soient transférées et soumises à une politique de confidentialité différente.</font></font></p>
<h3><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Forces de l'ordre</font></font></h3>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Dans certaines circonstances, la Société peut être tenue de divulguer vos données personnelles si la loi l'exige ou en réponse à des demandes valables d'autorités publiques (par exemple, un tribunal ou une agence gouvernementale).</font></font></p>
<h3><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Autres exigences légales</font></font></h3>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">La Société peut divulguer vos données personnelles en croyant de bonne foi qu'une telle action est nécessaire pour&nbsp;:</font></font></p>
<ul>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Respecter une obligation légale</font></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Protéger et défendre les droits ou la propriété de la Société</font></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Prévenir ou enquêter sur d'éventuels actes répréhensibles en rapport avec le Service</font></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Protéger la sécurité personnelle des Utilisateurs du Service ou du public</font></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Protégez-vous contre la responsabilité légale</font></font></li>
</ul>
<h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Sécurité de vos données personnelles</font></font></h2>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">La sécurité de vos données personnelles est importante pour nous, mais n'oubliez pas qu'aucune méthode de transmission sur Internet ou méthode de stockage électronique n'est sécurisée à 100 %. </font><font style="vertical-align: inherit;">Bien que nous nous efforcions d'utiliser des moyens commercialement acceptables pour protéger vos données personnelles, nous ne pouvons garantir leur sécurité absolue.</font></font></p>
<h1><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Confidentialité des enfants</font></font></h1>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Notre service ne s'adresse pas aux personnes de moins de 13 ans. Nous ne collectons pas sciemment d'informations personnellement identifiables auprès de personnes de moins de 13 ans. Si vous êtes un parent ou un tuteur et que vous savez que votre enfant nous a fourni des données personnelles, veuillez Nous contacter. </font><font style="vertical-align: inherit;">Si nous apprenons que nous avons collecté des données personnelles auprès d'une personne de moins de 13 ans sans vérification du consentement parental, nous prenons des mesures pour supprimer ces informations de nos serveurs.</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Si nous devons nous fier au consentement comme base légale pour le traitement de vos informations et que votre pays exige le consentement d'un parent, nous pouvons exiger le consentement de votre parent avant de collecter et d'utiliser ces informations.</font></font></p>
<h1><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Liens vers d'autres sites Web</font></font></h1>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Notre service peut contenir des liens vers d'autres sites Web qui ne sont pas exploités par nous. </font><font style="vertical-align: inherit;">Si vous cliquez sur un lien tiers, vous serez dirigé vers le site de ce tiers. </font><font style="vertical-align: inherit;">Nous vous conseillons vivement de consulter la politique de confidentialité de chaque site que vous visitez.</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Nous n'avons aucun contrôle et n'assumons aucune responsabilité quant au contenu, aux politiques de confidentialité ou aux pratiques des sites ou services tiers.</font></font></p>
<h1><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Modifications de cette politique de confidentialité</font></font></h1>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Nous pouvons mettre à jour notre politique de confidentialité de temps à autre. </font><font style="vertical-align: inherit;">Nous vous informerons de tout changement en publiant la nouvelle politique de confidentialité sur cette page.</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Nous vous informerons par e-mail et/ou par un avis visible sur notre service, avant que le changement ne devienne effectif et mettrons à jour la date de «&nbsp;dernière mise à jour&nbsp;» en haut de cette politique de confidentialité.</font></font></p>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Il vous est conseillé de consulter périodiquement cette politique de confidentialité pour tout changement. </font><font style="vertical-align: inherit;">Les modifications apportées à cette politique de confidentialité entrent en vigueur lorsqu'elles sont publiées sur cette page.</font></font></p>
<h1><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Nous contacter</font></font></h1>
<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Si vous avez des questions concernant cette politique de confidentialité, vous pouvez nous contacter&nbsp;:</font></font></p>
<ul>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Par courriel : pas.parent@outlook.com</font></font></li>
</ul>

</div>
</div>
</template>
<script lang="js">
    export default {
        name: 'Policy',
    }
</script>
<style lang="scss">
.page{
    overflow: auto;
    position: fixed;
    height: 100%;
    text-align: left;
    padding: 10px;

    h1{
        font-size: 1.5em;
        font-weight: bold;
        margin-bottom: 10px;
    }
    p{
        font-size: 1em;
        margin-bottom: 10px;
    }
    .tab-content{
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        margin-bottom: 10px;
    }
}
</style>
